### ISSUE TITLE
[Numpy, Subclass] Numpyのサブクラス化

### ISSUE THREAD

**Issue by karupagyu** [karupagyu/tips#4]
実装例

```python
import numpy as np

class DetResults(np.ndarray):
    # [person][x,y,w,h,cls,score]
    def __new__(cls, ndarr):
        assert isinstance(ndarr, np.ndarray), \
            'type {} cannot be generated to detresults.'.format(type(ndarr))
        return ndarr.view(cls)  # メモリ参照

    @property
    def tlbr_array(self) -> np.ndarray:
        return np.asarray(self[:, 4])

    @property
    def objectness_sc(self) -> np.ndarray:
        return self[:, 5].view()
```

**Comment by molla1998** [comment]
I am working on it.

**Comment by molla1998** [comment]
`import numpy as np

class DetResults(np.ndarray):
    # [person][x,y,w,h,cls,score]
    def __new__(cls, ndarr):
        assert isinstance(ndarr, np.ndarray),"type {} cannot be generated to detresults.".format(type(ndarr))
        return ndarr.view(cls)  # メモリ参照

    
    def tlbr_array(self):
        return np.asarray(self[:, 4])

    
    def objectness_sc(self):
        return self[:, 5].view()
person=np.array([['x','y','w','h','cls','score']])
S=DetResults(person)
p=S.tlbr_array()
print(S.tlbr_array())
print(S.objectness_sc())
`
